The create ship function implementation completed
MEHBUB7867/Battleships pull request #2
Opened 2021-09-24 08:00 UTC by MEHBUB7867

2021-09-27 11:11 UTC, Pragya28 requested changes

2021-09-27 11:11 UTC, Pragya28 commented on battleship.py
> +        c1=[]
Use a proper variable name in place of c1.

2021-09-27 13:27 UTC, MEHBUB7867 commented on battleship.py
> +        c1=[]
Mam, modified the proper variable name.

2021-09-28 08:48 UTC, Pragya28 reviewed
Good Work @MEHBUB7867.

2021-09-29 10:07 UTC, merged