Implementation of Check ship is completed.
MEHBUB7867/Battleships pull request #3
Opened 2021-09-25 10:23 UTC by MEHBUB7867

2021-09-27 11:18 UTC, Pragya28 requested changes

2021-09-27 11:18 UTC, Pragya28 commented on battleship.py
> +            return False
Reduce the number of lines in the function by checking the not equal condition and returning False, and returning True on completion of the loop.

2021-09-27 11:18 UTC, Pragya28 commented on battleship.py
> +        if(grid[i[0]][i[1]]==1):
Use variable name instead of the number.

2021-09-27 13:26 UTC, MEHBUB7867 commented on battleship.py
> +            return False
Mam, I have modified the code

2021-09-27 13:26 UTC, MEHBUB7867 commented on battleship.py
> +        if(grid[i[0]][i[1]]==1):
Variable name is assigned.

2021-09-28 08:52 UTC, Pragya28 requested changes

2021-09-28 08:52 UTC, Pragya28 commented on battleship.py
> +            return True
Did you test the function after updating @MEHBUB7867?
Please test the function again and make necessary changes if it gives an error.

2021-09-28 09:00 UTC, Pragya28 requested changes
Please commit these changes on pull request #4.

2021-09-28 09:00 UTC, Pragya28 commented on battleship.py
> +        return board
Did you test the function after updating @MEHBUB7867?
Please test the function and make necessary changes in case of errors.

2021-09-28 09:00 UTC, Pragya28 commented on battleship.py
> +        board=grid
This assignment is irrelevant and incorrect. Please work on the grid variable directly.

2021-09-28 11:38 UTC, MEHBUB7867 commented on battleship.py
> +            return True
Mam, I had changed the code.

2021-09-28 11:39 UTC, MEHBUB7867 commented on battleship.py
> +        board=grid
Mam I had modified the addships function.

2021-09-28 12:13 UTC, Pragya28 reviewed
Good Work @MEHBUB7867.

2021-09-29 10:08 UTC, merged