Implemented Add ships function
MEHBUB7867/Battleships pull request #4
Opened 2021-09-26 05:52 UTC by MEHBUB7867

2021-09-27 11:27 UTC, Pragya28 requested changes

2021-09-27 11:27 UTC, Pragya28 commented on battleship.py
> +        if checkShip(board,ship)==True:
No need of equating with True if a function returns boolean.

2021-09-27 12:27 UTC, MEHBUB7867 commented on battleship.py
> +        if checkShip(board,ship)==True:
Mam, I had modified the code in the line 119

2021-09-28 11:56 UTC, Pragya28 reviewed
Good Work @MEHBUB7867.

2021-09-29 10:11 UTC, merged